---
title: "Assignment 3: Plotting with Factors"
output:
  html_document:
    number_sections: false
    toc: no
---

**Due**: 4 February, 11:00 pm

**Weight**: This assignment is worth 4% of your final grade.

**Purpose**: The purpose of this assignment is to learn how to handle categorical data (specifically factors) for exploratory analysis and plotting with the **ggplot2** library in R.

**Skills & Knowledge**: After completing these exercises, you should be able to:

- Reorder factor variables based on other variables in a data frame.
- Rename factor variables.
- Create new factor variables from existing ones.
- Reorder factors within a **ggplot2** plot.

**Assessment**: This assignment is graded for completion. Credit will be allocated in proportion to the percentage of the assignment completed by the due date. No more than 2 late days can be used on any one assignment.

**Tasks**:

1. **Read**: Open up a notebook (physical, digital...whatever you take notes in best), and **take notes** while you go through the [readings for this week](r4-amounts-proportions.html).

2. **Exercises**: Take notes while you the entire [Categorical Data in the Tidyverse](https://www.datacamp.com/courses/categorical-data-in-the-tidyverse) course. You should go through all four lessons in the course.

3. **Report**: When you have completed the above exercises, go to the "Assignment Submission" page on Blackboard and write three things from your notes that you learned while going through these readings and exercises.
